services: # dockers compose expects
  static_html:
    # image: python:3.13.4-slim-bullseye
    build:
      context: ./static_html
      dockerfile: static.Dockerfile
    ports:
      - 8000:8000
      - 3000:8000
    command: python -m http.server 8000
    volumes:
      - ./static_html/src:/app
